[setting.btcSettlementDelay]
defaultValue = "15"

[setting.btcSettlementWindowDuration]
defaultValue = "60"

[setting.btcPriceWindowDuration]
defaultValue = "600"

[setting.pythPriceVerificationAddress]
defaultValue = "0xff1a0f4744e8582DF1aE09D5611b887B6a12925C"

[setting.pythEthFeedId]

[setting.pythFeedUrl]

[setting.settlementReward]
defaultValue = "0"

[setting.btcSettlementDeviationTolerance]
defaultValue = "0.05"

[setting.settlementMinimumUsdExchangeAmount]
defaultValue = "0.000001"

[setting.settlementMaxRoundingLoss]
defaultValue = "0.000001"
