name = "synthetix-omnibus"
version = "3.2.1"
description = "Includes the full synthetix system with configurations applied"
include = [
    "tomls/settings-testnet.toml",
    "tomls/core.toml",
    "tomls/permissions.toml",
    "tomls/collaterals/snx.toml",
    "tomls/collaterals/weth.toml",
    "tomls/pools/spartan-council.toml",
    "tomls/pools/passive-snx.toml",
    "tomls/markets/spot/eth.toml",
    "tomls/markets/spot/btc.toml",
    "tomls/markets/spot/link.toml",
    "tomls/markets/perps/eth.toml",
    "tomls/permit-all-createPool.toml",
    "tomls/permit-all-registerMarket.toml",
    "tomls/permit-all-createAccount.toml", # used for perps market
    "tomls/permit-all-transferCrossChain.toml",
]

[setting.owner]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

[setting.weth_address]
defaultValue = "0x4200000000000000000000000000000000000006"

[setting.snx_address]
defaultValue = "0x2E5ED97596a8368EB9E44B1f3F25B2E813845303"

[setting.snx_aggregator_address]
defaultValue = "0x89A7630f46B8c35A7fBBC4f6e4783f1E2DC715c6"

[setting.snx_liquidation_reward]
defaultValue = "10000000000000000000"

[setting.minimum_liquidity_ratio]
defaultValue = "2000000000000000000"

[setting.account_timeout_withdraw]
defaultValue = "86400"

[setting.deployer]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

[setting.sc_pool_id]
defaultValue = "1"

[setting.sc_pool_owner]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

[setting.snx_pool_id]
defaultValue = "69"

[setting.snx_pool_owner]
defaultValue = "<%= settings.sc_pool_owner %>"

[setting.ccip_router]
defaultValue = "0xeb52e9ae4a9fb37172978642d4c141ef53876f26"

[setting.ccip_token_pool]
defaultValue = "0x7a81e36b40b0a778afb2ae3c8384b6195233d093"

# Aggregators for markets

[setting.link_aggregator_address]
defaultValue = "0x69C5297001f38cCBE30a81359da06E5256bd28B9"

[setting.btc_aggregator_address]
defaultValue = "0xC16679B963CeB52089aD2d95312A5b85E318e9d2"

[setting.eth_aggregator_address]
defaultValue = "0x57241A37733983F97C4Ab06448F244A1E0Ca0ba8"

# Perps Global Configuration
# TODO: move these into perps-factory once settings support max uint
[invoke.setPerpsMaxCollateralForSnxUsd]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxCollateralAmount"
args = [
  "0", 
  "<%= MaxUint256 %>"
]
depends = ["provision.perpsFactory"]

[invoke.setPerpsMaxCollateralForSynthMarketId]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxCollateralAmount"
args = [
  "<%= extras.synth_eth_market_id %>", 
  "<%= MaxUint256 %>"
]
depends = ["invoke.createEthSynth", "provision.perpsFactory"]

[invoke.setPerpsSynthDeductionPriorityPerps]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSynthDeductionPriority"
args = [["0", "<%= extras.synth_eth_market_id %>"]]
depends = ["invoke.createEthSynth", "provision.perpsFactory"]

[setting.perpsMinLiquidationReward]
defaultValue = "100"

[setting.perpsMaxLiquidationReward]
defaultValue = "500"

# ETH Perps Configuration

[setting.perpsEthSkewScale]
defaultValue = "100000"

[setting.perpsEthMaxFundingVelocity]
defaultValue = "9"

[setting.perpsEthMakerFeeRatio]
defaultValue = "0.0007"

[setting.perpsEthTakerFeeRatio]
defaultValue = "0.0003"

[setting.perpsEthMaxMarketSize]
defaultValue = "10000"

[setting.perpsEthInitialMarginRatio]
defaultValue = "2"

[setting.perpsEthMaintenanceMarginFraction]
defaultValue = "1"

[setting.perpsEthLiquidationRewardRatioD18]
defaultValue = "0.01"

[setting.perpsEthMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1"

[setting.perpsEthMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsEthMinimumPositionMargin]
defaultValue = "1"

[setting.perpsEthLockedOiRatio]
defaultValue = "0.1"

# ETH Synth Configuration

[setting.synthEthAsyncFixedFee]
defaultValue = "0.001"

[setting.synthEthMaxMarketCollateral]
defaultValue = "100"

[setting.synthEthSkewScale]
defaultValue = "100000"

[setting.synthEthWrapFee]
defaultValue = "0.0001"

[setting.synthEthUnwrapFee]
defaultValue = "0.0001"

[setting.ethSettlementWindowDuration]
defaultValue = "600"

# Pyth settlement strategy config
[setting.pythFeedUrl]
defaultValue = "https://api.synthetix.io/pyth-testnet/api/get_vaa_ccip?data={data}"

[setting.pythEthFeedId]
defaultValue = "0xca80ba6dc32e08d06f1aa886011eed1d77c77be9eb761cc10d72b7d0a2fd57a6"

[setting.priceWindowDuration]
defaultValue = "180"

[invoke.setScPoolConfig]
target = ["system.CoreProxy"]
fromCall.func = "getPoolOwner"
fromCall.args = ["<%= settings.sc_pool_id %>"]
func = "setPoolConfiguration"
args = [
    "<%= settings.sc_pool_id %>",
    [
        { marketId = "<%= extras.synth_btc_market_id %>", weightD18 = 1, maxDebtShareValueD18 = "<%= parseEther('1') %>" },
        { marketId = "<%= extras.synth_eth_market_id %>", weightD18 = 1, maxDebtShareValueD18 = "<%= parseEther('1') %>" },
        { marketId = "<%= extras.synth_link_market_id %>", weightD18 = 1, maxDebtShareValueD18 = "<%= parseEther('1') %>" },
        { marketId = "<%= extras.perps_eth_market_id %>", weightD18 = 1, maxDebtShareValueD18 = "<%= parseEther('1') %>" }
    ],
]

depends=["invoke.createScPool", "invoke.createEthSynth", "invoke.createBtcSynth", "invoke.createLinkSynth", "invoke.createEthPerpsMarket"]
