name = "synthetix-omnibus"
version = "3.2.0-xchain.0"
description = "Includes the full synthetix system with configurations applied"
include = [
    "tomls/settings.toml",
    "tomls/core.toml",
    "tomls/permissions.toml",
    "tomls/collaterals/snx.toml",
    "tomls/collaterals/weth.toml",
    "tomls/pools/spartan-council.toml",
    "tomls/permit-all-createPool.toml",
    "tomls/permit-all-registerMarket.toml",
]

[setting.owner]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

[setting.salt]
defaultValue = "0x78636861696e7866657273000000000000000000000000000000000000000000"

[setting.bundleSalt]
defaultValue = "xchainxfers"

[setting.target_preset]
defaultValue = "xchainxfers"

[setting.weth_address]
defaultValue = "0x7b79995e5f793a07bc00c21412e50ecae098e7f9"

[setting.eth_aggregator_address]
defaultValue = "0x694AA1769357215DE4FAC081bf1f309aDC325306"

[setting.snx_address]
defaultValue = "0xd61c1bbd33744a5dab3b7843758b766c07e1fb97"

[setting.snx_aggregator_address]
defaultValue = "0xc0F82A46033b8BdBA4Bb0B0e28Bc2006F64355bC"

[setting.snx_liquidation_reward]
defaultValue = "10000000000000000000"

[setting.weth_liquidation_reward]
defaultValue = "10000000000000000000"

[setting.minimum_liquidity_ratio]
defaultValue = "2000000000000000000"

[setting.account_timeout_withdraw]
defaultValue = "0"

[setting.deployer]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

[setting.sc_pool_id]
defaultValue = "1"

[setting.sc_pool_owner]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

# Chainlink Configuration

[setting.ccip_router]
defaultValue = "0x366e98df2881543185ece04dacffde417c7d2f1d"

[setting.ccip_token_pool]
defaultValue = "0x72621601257da0c36c99ae84e2817b2d82f4f1ad"

[setting.chainlink_funcs]
defaultValue = "0x366e98df2881543185ece04dacffde417c7d2f1d"