name = "synthetix-omnibus"
version = "3.2.0-xchain.0"
description = "Includes the full synthetix system with configurations applied"
include = [
    "tomls/settings.toml",
    "tomls/core.toml",
    "tomls/permissions.toml",
    "tomls/collaterals/snx.toml",
    "tomls/collaterals/weth.toml",
    "tomls/pools/spartan-council.toml",
    "tomls/permit-all-createPool.toml",
    "tomls/permit-all-registerMarket.toml",
]

[setting.owner]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

[setting.salt]
defaultValue = "0x78636861696e7866657273000000000000000000000000000000000000000000"

[setting.bundleSalt]
defaultValue = "xchainxfers"

[setting.target_preset]
defaultValue = "xchainxfers"

[setting.weth_address]
defaultValue = "0x4200000000000000000000000000000000000006"

[setting.eth_aggregator_address]
defaultValue = "0x57241A37733983F97C4Ab06448F244A1E0Ca0ba8"

[setting.snx_address]
defaultValue = "0x2E5ED97596a8368EB9E44B1f3F25B2E813845303"

[setting.snx_aggregator_address]
defaultValue = "0x89A7630f46B8c35A7fBBC4f6e4783f1E2DC715c6"

[setting.snx_liquidation_reward]
defaultValue = "10000000000000000000"

[setting.weth_liquidation_reward]
defaultValue = "10000000000000000000"

[setting.minimum_liquidity_ratio]
defaultValue = "2000000000000000000"

[setting.account_timeout_withdraw]
defaultValue = "0"

[setting.deployer]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

[setting.sc_pool_id]
defaultValue = "1"

[setting.sc_pool_owner]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

# Chainlink Configuration

[setting.ccip_router]
defaultValue = "0x8ec5ad6cb5496dae52d2e80cd59fa78d066626d6"

[setting.ccip_token_pool]
defaultValue = "0x41eb1dc55fa7d124727e5810e1a78e2ab495a81a"

[setting.chainlink_funcs]
defaultValue = "0x8ec5ad6cb5496dae52d2e80cd59fa78d066626d6"