name = "synthetix-omnibus"
version = "3.0.0"
description = "Includes the full synthetix system with configurations applied"
include = [
    "tomls/settings.toml",
    "tomls/core.toml",
    "tomls/permissions.toml",
    "tomls/collaterals/snx.toml",
    # "tomls/collaterals/weth.toml",
    "tomls/pools/spartan-council.toml",
]

[setting.owner]
defaultValue = "0x0f9019dD6821f74FC8Ade3Cd32246859BA20a135"

[setting.snx_address]
defaultValue = "0x8700dAec35aF8Ff88c16BdF0418774CB3D7599B4"

[setting.snx_aggregator_address]
defaultValue = "0x2FCF37343e916eAEd1f1DdaaF84458a359b53877"

[setting.snx_liquidation_reward]
defaultValue = "10000000000000000000"

[setting.minimum_liquidity_ratio]
defaultValue = "2000000000000000000"

[setting.account_timeout_withdraw]
defaultValue = "86400"

[setting.deployer]
defaultValue = "0x302d2451d9f47620374B54c521423Bf0403916A2"

[setting.sc_pool_id]
defaultValue = "1"

[setting.sc_pool_owner]
defaultValue = "0x302d2451d9f47620374B54c521423Bf0403916A2"
