name = "synthetix-omnibus"
version = "3.2.0-xchain.0"
description = "Includes the full synthetix system with configurations applied"
include = [
    "tomls/settings.toml",
    "tomls/core.toml",
    "tomls/permissions.toml",
    "tomls/collaterals/snx.toml",
    "tomls/collaterals/weth.toml",
    "tomls/pools/spartan-council.toml",
    "tomls/permit-all-createPool.toml",
    "tomls/permit-all-registerMarket.toml",
]

[setting.owner]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

[setting.salt]
defaultValue = "0x78636861696e7866657273000000000000000000000000000000000000000000"

[setting.bundleSalt]
defaultValue = "xchainxfers"

[setting.target_preset]
defaultValue = "xchainxfers"

[setting.weth_address]
defaultValue = "0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa"

[setting.eth_aggregator_address]
defaultValue = "0x0715A7794a1dc8e42615F059dD6e406A6594651A"

[setting.snx_address]
defaultValue = "0x99ad600dda7879CFD0FdC55124585603DEED0070"

[setting.snx_aggregator_address]
defaultValue = "0x1C2252aeeD50e0c9B64bDfF2735Ee3C932F5C408"

[setting.snx_liquidation_reward]
defaultValue = "10000000000000000000"

[setting.weth_liquidation_reward]
defaultValue = "10000000000000000000"

[setting.minimum_liquidity_ratio]
defaultValue = "2000000000000000000"

[setting.account_timeout_withdraw]
defaultValue = "0"

[setting.deployer]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

[setting.sc_pool_id]
defaultValue = "1"

[setting.sc_pool_owner]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

# Chainlink Configuration

[setting.ccip_router]
defaultValue = "0x70499c328e1e2a3c41108bd3730f6670a44595d1"

[setting.ccip_token_pool]
defaultValue = "0x56ffa3ae8bb98b120067b1be50136f681aa3addf"

[setting.chainlink_funcs]
defaultValue = "0x43a2a4c2ecb74ff45eca704a14111d8f2b1c0fa0"