name = "synthetix-omnibus"
version = "3.2.1-dev.5e6e7365"
description = "Includes the full synthetix system with configurations applied"
include = [
    "tomls/settings-testnet.toml",
    "tomls/core.toml",
    "tomls/permissions.toml",
    "tomls/collaterals/snx.toml",
    "tomls/collaterals/weth.toml",
    "tomls/pools/spartan-council.toml",
    "tomls/pools/passive-snx.toml",
    "tomls/markets/spot/eth.toml",
    "tomls/markets/spot/btc.toml",
    "tomls/markets/spot/link.toml",
    "tomls/markets/perps/eth.toml",
    "tomls/markets/perps/btc.toml",
    "tomls/permit-all-createPool.toml",
    "tomls/permit-all-registerMarket.toml",
    "tomls/permit-all-perps-createAccount.toml",
    "tomls/permit-all-transferCrossChain.toml",
    "tomls/settings/optimism-goerli/eth.toml",
    "tomls/settings/optimism-goerli/btc.toml",
    "tomls/settings/optimism-goerli/link.toml",
]

[setting.owner]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

[setting.weth_address]
defaultValue = "0x4200000000000000000000000000000000000006"

[setting.snx_address]
defaultValue = "0x2E5ED97596a8368EB9E44B1f3F25B2E813845303"

[setting.snx_aggregator_address]
defaultValue = "0x89A7630f46B8c35A7fBBC4f6e4783f1E2DC715c6"

[setting.snx_liquidation_reward]
defaultValue = "10000000000000000000"

[setting.minimum_liquidity_ratio]
defaultValue = "2000000000000000000"

[setting.account_timeout_withdraw]
defaultValue = "86400"

[setting.deployer]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

[setting.sc_pool_id]
defaultValue = "1"

[setting.sc_pool_owner]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

[setting.snx_pool_id]
defaultValue = "69"

[setting.snx_pool_owner]
defaultValue = "<%= settings.sc_pool_owner %>"

[setting.ccip_router]
defaultValue = "0xeb52e9ae4a9fb37172978642d4c141ef53876f26"

[setting.ccip_token_pool]
defaultValue = "0xd23c2ef3a533040b57cadaf33ccb111edbaca018"

# Perps Global Configuration
# TODO: move these into perps-factory once settings support max uint

[invoke.setPerpsMaxCollateralForSnxUsd]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxCollateralAmount"
args = [
  "0",
  "<%= MaxUint256 %>"
]
depends = ["provision.perpsFactory"]

[invoke.setPerpsMaxCollateralForSynthMarketId]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxCollateralAmount"
args = [
  "<%= extras.synth_eth_market_id %>",
  "<%= MaxUint256 %>"
]
depends = ["invoke.createEthSynth", "provision.perpsFactory"]

[invoke.setPerpsSynthDeductionPriorityPerps]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSynthDeductionPriority"
args = [["0", "<%= extras.synth_eth_market_id %>"]]
depends = ["invoke.createEthSynth", "provision.perpsFactory"]

[setting.perpsMinLiquidationReward]
defaultValue = "1"

[setting.perpsMaxLiquidationReward]
defaultValue = "500"

[invoke.setPerpsProxyCustomTransactorOnEthSynthMarket]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_eth_market_id %>"]
func = "setCustomTransactorFees"
args = [
  "<%= extras.synth_eth_market_id %>",
  "<%= imports.perpsFactory.contracts.PerpsMarketProxy.address %>",
  "<%= parseEther('0.0001') %>"
]
depends=["provision.perpsFactory", "invoke.createEthSynth"]

[invoke.setPerpsProxyCustomTransactorOnBtcSynthMarket]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_btc_market_id %>"]
func = "setCustomTransactorFees"
args = [
  "<%= extras.synth_btc_market_id %>",
  "<%= imports.perpsFactory.contracts.PerpsMarketProxy.address %>",
  "<%= parseEther('0.0001') %>"
]
depends=["provision.perpsFactory", "invoke.createBtcSynth"]

# Pyth settlement strategy config
[setting.pythFeedUrl]
defaultValue = "https://api.synthetix.io/pyth-testnet/api/get_vaa_ccip?data={data}"

[setting.pythPriceVerificationAddress]
defaultValue = "0xff1a0f4744e8582DF1aE09D5611b887B6a12925C"

[setting.priceWindowDuration]
defaultValue = "180"

[invoke.setScPoolConfig]
target = ["system.CoreProxy"]
fromCall.func = "getPoolOwner"
fromCall.args = ["<%= settings.sc_pool_id %>"]
func = "setPoolConfiguration"
args = [
    "<%= settings.sc_pool_id %>",
    [
        { marketId = "<%= extras.synth_btc_market_id %>", weightD18 = 1, maxDebtShareValueD18 = "<%= parseEther('1') %>" },
        { marketId = "<%= extras.synth_eth_market_id %>", weightD18 = 1, maxDebtShareValueD18 = "<%= parseEther('1') %>" },
        { marketId = "<%= extras.synth_link_market_id %>", weightD18 = 1, maxDebtShareValueD18 = "<%= parseEther('1') %>" },
        { marketId = "<%= imports.perpsFactory.extras.superMarketId %>", weightD18 = 1, maxDebtShareValueD18 = "<%= parseEther('1') %>" }
    ],
]

depends=["invoke.createScPool", "invoke.createEthSynth", "invoke.createBtcSynth", "invoke.createLinkSynth", "provision.perpsFactory"]
