name = "synthetix-omnibus"
version = "3.2.1"
description = "Includes the full synthetix system with configurations applied"
include = [
    "tomls/settings-testnet.toml",
    "tomls/core.toml",
    "tomls/permissions.toml",
    "tomls/collaterals/weth.toml",
    "tomls/pools/spartan-council.toml",
    "tomls/permit-all-createPool.toml",
    "tomls/permit-all-registerMarket.toml",
    "tomls/permit-all-transferCrossChain.toml",
]

[setting.owner]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

[setting.weth_address]
defaultValue = "0x7b79995e5f793a07bc00c21412e50ecae098e7f9"

[setting.eth_aggregator_address]
defaultValue = "0x694AA1769357215DE4FAC081bf1f309aDC325306"

[setting.weth_liquidation_reward]
defaultValue = "10000000000000000000"

[setting.minimum_liquidity_ratio]
defaultValue = "2000000000000000000"

[setting.account_timeout_withdraw]
defaultValue = "86400"

[setting.deployer]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

[setting.sc_pool_id]
defaultValue = "1"

[setting.sc_pool_owner]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

[setting.ccip_router]
defaultValue = "0xd0daae2231e9cb96b94c8512223533293c3693bf"

[setting.ccip_token_pool]
defaultValue = "0x2291909e328dd00e6b3284730d478f39dbde4c88"