[setting.snx_package]
defaultValue = "synthetix:3.1.1"

[setting.owner]

[setting.target_preset]

[setting.salt]
defaultValue = "snax"

[setting.bundleSalt]
defaultValue = "snax"

[provision.system]
source = "<%= settings.snx_package %>"
targetPreset = "<%= settings.target_preset %>"
options.owner = "<%= settings.owner %>"
options.salt = "<%= settings.salt %>"
options.bundleSalt = "<%= settings.bundleSalt %>"
