[setting.snx_package]
defaultValue = "synthetix:3.0.4-dev.7f1ec775"

[setting.owner]

[setting.salt]
defaultValue = "snax"

[provision.system]
source = "<%= settings.snx_package %>"
options.owner = "<%= settings.owner %>"
options.salt = "<%= settings.salt %>"
