include = [
  "./spot-factory.toml"
]

[setting.perps_market_package]
defaultValue = "synthetix-perps-market:3.2.1-dev.5e6e7365"

[provision.perpsFactory]
source = "<%= settings.perps_market_package %>"
targetPreset = "main"
options.coreProxyOwner = "<%= settings.owner %>"
options.owner = "<%= settings.owner %>"
options.salt = "alpha"
options.synthetixPackage = "<%= settings.snx_package %>"
options.spotMarketPackage = "<%= settings.spot_market_package %>"

depends = ["provision.spotFactory"]

[invoke.setPerpsLiquidationRewardLimits]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationRewardGuards"
args = [
  "<%= parseEther(settings.perpsMinLiquidationReward) %>",
  "<%= parseEther(settings.perpsMaxLiquidationReward) %>"
]
depends = ["provision.perpsFactory"]