include = [
  "../spot-factory.toml",
]

[setting.link_aggregator_address]

[invoke.registerSynthLinkOracleManager]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
   # 3 = chainlink aggregator type
   3,
   # 3 parameters are: address of the chainlink oracle
   "<%= defaultAbiCoder.encode(['address', 'uint256', 'uint8'], [settings.link_aggregator_address, 0, 8]) %>",
   []
]

extra.synth_link_oracle_id.event = "NodeRegistered"
extra.synth_link_oracle_id.arg = 0

depends = [
 "provision.system"
]

[invoke.createLinkSynth]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "owner"
func = "createSynth"
args = ["Synthetic Chainlink Token", "snxLINK", "<%= settings.owner %>"]

extra.synth_link_market_id.event = "SynthRegistered"
extra.synth_link_market_id.arg = 0

extra.synth_link_token_address.event = "SynthRegistered"
extra.synth_link_token_address.arg = 1

depends = ["provision.spotFactory"]

[invoke.setSynthPriceLink]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_link_market_id %>"]

func = "updatePriceData"
args = [
  "<%= extras.synth_link_market_id %>", 
  "<%= extras.synth_link_oracle_id %>", 
  "<%= extras.synth_link_oracle_id %>"
]

depends = ["invoke.createLinkSynth", "invoke.registerSynthLinkOracleManager"]