[setting.ethSettlementDelay]
defaultValue = "15"

[setting.ethSettlementWindowDuration]
defaultValue = "60"

[setting.ethPriceWindowDuration]
defaultValue = "600"

[setting.pythPriceVerificationAddress]

[setting.pythEthFeedId]

[setting.pythFeedUrl]

[setting.settlementReward]
defaultValue = "0"

[setting.ethSettlementDeviationTolerance]
defaultValue = "0.05"

[setting.settlementMinimumUsdExchangeAmount]
defaultValue = "0.000001"

[setting.settlementMaxRoundingLoss]
defaultValue = "0.000001"
