name: Simulate Release

on:
  pull_request: {}
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CANNON_SETTINGS: ${{ secrets.CANNON_SETTINGS }}
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
    strategy:
      matrix:
        network: [mainnet, optimism-mainnet, goerli, optimism-goerli, base-goerli]
        manifest: [omnibus.toml]
    steps:
      - name: Install Foundry (Cannon)
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: anvil -V
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: |
          npm i -g @usecannon/cli
      - run: |
          npx @usecannon/cli plugin add cannon-plugin-router
      - run: |
          npx @usecannon/cli build omnibus-${{ matrix.network }}.toml --upgrade-from synthetix-omnibus:latest --provider-url https://${{ matrix.network }}.infura.io/v3/$INFURA_API_KEY --dry-run
